import csv
import random
import os

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
METADATA_PATH = os.path.join(project_root, "data", "movie_metadata.csv")

movies = [
    # Initial 30 + newly added ones to make it ~100
    ("The Dark Knight", "2008", "Action|Crime|Drama", "18+", "A+", "Batman faces the Joker — a criminal mastermind who seeks to undermine Gotham's population in anarchic chaos.", "Christopher Nolan", "Christian Bale, Heath Ledger", "152 min"),
    ("Inception", "2010", "Action|Sci-Fi|Thriller", "Teen", "A+", "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.", "Christopher Nolan", "Leonardo DiCaprio, Joseph Gordon-Levitt", "148 min"),
    ("The Shawshank Redemption", "1994", "Drama", "Teen", "A+", "Two imprisoned men bond over years finding solace and eventual redemption through acts of common decency.", "Frank Darabont", "Tim Robbins, Morgan Freeman", "142 min"),
    ("Forrest Gump", "1994", "Drama|Romance", "Family", "A+", "The presidencies of Kennedy and Johnson through the eyes of an Alabama man with an extraordinary life story.", "Robert Zemeckis", "Tom Hanks, Robin Wright", "142 min"),
    ("The Godfather", "1972", "Crime|Drama", "18+", "A+", "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.", "Francis Ford Coppola", "Marlon Brando, Al Pacino", "175 min"),
    ("Pulp Fiction", "1994", "Crime|Drama", "18+", "A", "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in tales of violence and redemption.", "Quentin Tarantino", "John Travolta, Uma Thurman", "154 min"),
    ("Interstellar", "2014", "Adventure|Drama|Sci-Fi", "Teen", "A+", "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", "Christopher Nolan", "Matthew McConaughey, Anne Hathaway", "169 min"),
    ("The Lion King", "1994", "Animation|Adventure|Drama", "Family", "A+", "Lion prince Simba flees his kingdom only to learn the true meaning of responsibility and bravery.", "Roger Allers, Rob Minkoff", "Matthew Broderick, Jeremy Irons", "88 min"),
    ("Avengers: Endgame", "2019", "Action|Adventure|Sci-Fi", "Family", "A", "After Thanos decimates half the universe, the Avengers assemble one last time to reverse his actions.", "Anthony Russo, Joe Russo", "Robert Downey Jr., Chris Evans", "181 min"),
    ("Parasite", "2019", "Comedy|Drama|Thriller", "18+", "A+", "Greed and class discrimination threaten the symbiotic relationship between the wealthy Parks and the destitute Kims.", "Bong Joon Ho", "Song Kang-ho, Lee Sun-kyun", "132 min"),
    ("Spirited Away", "2001", "Animation|Adventure|Fantasy", "Family", "A+", "During her family's move, a sullen girl wanders into a world ruled by gods, witches, and spirits.", "Hayao Miyazaki", "Rumi Hiiragi, Miyu Irino", "125 min"),
    ("The Matrix", "1999", "Action|Sci-Fi", "Teen", "A", "A computer hacker learns the nature of his reality and joins a rebellion against the controllers of the universe.", "Lana Wachowski, Lilly Wachowski", "Keanu Reeves, Laurence Fishburne", "136 min"),
    ("Toy Story", "1995", "Animation|Adventure|Comedy", "Child Specific", "A+", "A cowboy doll is profoundly threatened and jealous when a new spaceman figure becomes his owner's favorite toy.", "John Lasseter", "Tom Hanks, Tim Allen", "81 min"),
    ("Finding Nemo", "2003", "Animation|Adventure|Comedy", "Child Specific", "A+", "After his son is captured in the Great Barrier Reef, a clownfish sets out on a journey to bring him home.", "Andrew Stanton, Lee Unkrich", "Albert Brooks, Ellen DeGeneres", "100 min"),
    ("Up", "2009", "Animation|Adventure|Comedy", "Child Specific", "A+", "Seventy-eight year old Carl Fredricksen and a young boy travel to South America in a flying house.", "Pete Docter, Bob Peterson", "Edward Asner, Jordan Nagai", "96 min"),
    ("Coco", "2017", "Animation|Adventure|Comedy", "Child Specific", "A", "A young boy and his family's generations-old ban on music leads to his journey to the Land of the Dead.", "Lee Unkrich, Adrian Molina", "Anthony Gonzalez, Gael García Bernal", "105 min"),
    ("The Avengers", "2012", "Action|Adventure|Sci-Fi", "Family", "B+", "Earth's mightiest heroes must come together and learn to fight as a team to stop the mischievous Loki.", "Joss Whedon", "Robert Downey Jr., Chris Evans", "143 min"),
    ("Joker", "2019", "Crime|Drama|Thriller", "18+", "A", "A gritty character study of Arthur Fleck, a man disregarded by society who becomes the iconic Batman villain.", "Todd Phillips", "Joaquin Phoenix, Robert De Niro", "122 min"),
    ("Black Panther", "2018", "Action|Adventure|Sci-Fi", "Family", "B+", "T'Challa returns home to Wakanda to take the throne but faces a powerful enemy who challenges his claim.", "Ryan Coogler", "Chadwick Boseman, Michael B. Jordan", "134 min"),
    ("Whiplash", "2014", "Drama|Music", "Teen", "A+", "A promising young drummer enrolls at a cut-throat music conservatory where his teacher will stop at nothing.", "Damien Chazelle", "Miles Teller, J.K. Simmons", "106 min"),
    ("La La Land", "2016", "Comedy|Drama|Music", "Family", "A", "A jazz musician and an aspiring actress fall in love while struggling to pursue their dreams in Los Angeles.", "Damien Chazelle", "Ryan Gosling, Emma Stone", "128 min"),
    ("Get Out", "2017", "Horror|Mystery|Thriller", "18+", "A", "A young African-American visits his white girlfriend's parents for the weekend where he uncovers a disturbing secret.", "Jordan Peele", "Daniel Kaluuya, Allison Williams", "104 min"),
    ("Mad Max: Fury Road", "2015", "Action|Adventure|Sci-Fi", "18+", "A", "In a post-apocalyptic world, Max helps a rebellious Imperator escape a tyrannical warlord.", "George Miller", "Tom Hardy, Charlize Theron", "120 min"),
    ("The Grand Budapest Hotel", "2014", "Adventure|Comedy|Crime", "Teen", "B+", "The adventures of a legendary hotel concierge and his lobby boy in the between-the-wars period.", "Wes Anderson", "Ralph Fiennes, F. Murray Abraham", "99 min"),
    ("A Beautiful Mind", "2001", "Biography|Drama", "Teen", "A", "A biopic of mathematician John Nash, whose discoveries were groundbreaking but who also suffered from paranoid schizophrenia.", "Ron Howard", "Russell Crowe, Ed Harris", "135 min"),
    ("Schindler's List", "1993", "Biography|Drama|History", "18+", "A+", "In German-occupied Poland, Oskar Schindler gradually becomes concerned for his Jewish workforce after seeing their persecution.", "Steven Spielberg", "Liam Neeson, Ralph Fiennes", "195 min"),
    ("Frozen", "2013", "Animation|Adventure|Comedy", "Child Specific", "B+", "When the newly crowned Queen Elsa accidentally uses her power to turn Arendelle into winter, Anna sets off to find her.", "Chris Buck, Jennifer Lee", "Kristen Bell, Idina Menzel", "102 min"),
    ("Spider-Man: Into the Spider-Verse", "2018", "Animation|Action|Adventure", "Child Specific", "A+", "Miles Morales becomes Spider-Man, but soon teams with alternate-universe versions of Spider-Man.", "Bob Persichetti, Peter Ramsey, Rodney Rothman", "Shameik Moore, Jake Johnson", "117 min"),
    ("Everything Everywhere All at Once", "2022", "Action|Adventure|Comedy", "18+", "A+", "A middle-aged Chinese immigrant is swept up in an insane adventure where she can access the lives of parallel universe versions of herself.", "Daniel Kwan, Daniel Scheinert", "Michelle Yeoh, Ke Huy Quan", "139 min"),
    ("Oppenheimer", "2023", "Biography|Drama|History", "18+", "A+", "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", "Christopher Nolan", "Cillian Murphy, Emily Blunt", "180 min"),
    ("Dune: Part Two", "2024", "Action|Adventure|Sci-Fi", "Teen", "A+", "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.", "Denis Villeneuve", "Timothée Chalamet, Zendaya", "166 min"),
    ("The Silence of the Lambs", "1991", "Crime|Drama|Thriller", "18+", "A+", "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.", "Jonathan Demme", "Jodie Foster, Anthony Hopkins", "118 min"),
    ("Gladiator", "2000", "Action|Adventure|Drama", "18+", "A", "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", "Ridley Scott", "Russell Crowe, Joaquin Phoenix", "155 min"),
    ("Goodfellas", "1990", "Biography|Crime|Drama", "18+", "A+", "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.", "Martin Scorsese", "Robert De Niro, Ray Liotta, Joe Pesci", "145 min"),
    ("Fight Club", "1999", "Drama", "18+", "A+", "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.", "David Fincher", "Brad Pitt, Edward Norton", "139 min"),
    ("The Green Mile", "1999", "Crime|Drama|Fantasy", "18+", "A+", "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.", "Frank Darabont", "Tom Hanks, Michael Clarke Duncan", "189 min"),
    ("WALL-E", "2008", "Animation|Adventure|Family", "Child Specific", "A+", "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.", "Andrew Stanton", "Ben Burtt, Elissa Knight", "98 min"),
    ("How to Train Your Dragon", "2010", "Animation|Action|Adventure", "Child Specific", "A", "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself.", "Dean DeBlois, Chris Sanders", "Jay Baruchel, Gerard Butler", "98 min"),
    ("Inside Out", "2015", "Animation|Adventure|Comedy", "Family", "A+", "After young Riley is uprooted from her Midwest life, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate.", "Pete Docter, Ronnie Del Carmen", "Amy Poehler, Bill Hader", "95 min"),
    ("Spider-Man: Across the Spider-Verse", "2023", "Animation|Action|Adventure", "Teen", "A+", "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.", "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson", "Shameik Moore, Hailee Steinfeld", "140 min"),
    ("Dune", "2021", "Action|Adventure|Sci-Fi", "Teen", "A", "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset.", "Denis Villeneuve", "Timothée Chalamet, Rebecca Ferguson", "155 min"),
    ("The Prestige", "2006", "Drama|Mystery|Sci-Fi", "Teen", "A", "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion.", "Christopher Nolan", "Christian Bale, Hugh Jackman", "130 min"),
    ("Moana", "2016", "Animation|Adventure|Comedy", "Child Specific", "A", "In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana's island, she answers the Ocean's call.", "Ron Clements, John Musker", "Auli'i Cravalho, Dwayne Johnson", "107 min"),
    ("Harry Potter and the Philosopher's Stone", "2001", "Adventure|Family|Fantasy", "Family", "A", "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil.", "Chris Columbus", "Daniel Radcliffe, Rupert Grint, Emma Watson", "152 min"),
    ("The Lord of the Rings: The Fellowship of the Ring", "2001", "Action|Adventure|Drama", "Teen", "A+", "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.", "Peter Jackson", "Elijah Wood, Ian McKellen", "178 min"),
    ("The Lord of the Rings: The Return of the King", "2003", "Action|Adventure|Drama", "Teen", "A+", "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam.", "Peter Jackson", "Elijah Wood, Viggo Mortensen", "201 min"),
    ("Pirates of the Caribbean: The Curse of the Black Pearl", "2003", "Action|Adventure|Fantasy", "Teen", "A", "Blacksmith Will Turner teams up with eccentric pirate Captain Jack Sparrow to save his love.", "Gore Verbinski", "Johnny Depp, Geoffrey Rush", "143 min"),
    ("Jurassic Park", "1993", "Action|Adventure|Sci-Fi", "Teen", "A+", "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids.", "Steven Spielberg", "Sam Neill, Laura Dern", "127 min"),
    ("Iron Man", "2008", "Action|Adventure|Sci-Fi", "Teen", "A", "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor.", "Jon Favreau", "Robert Downey Jr., Gwyneth Paltrow", "126 min"),
    ("Guardians of the Galaxy", "2014", "Action|Adventure|Comedy", "Teen", "A", "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.", "James Gunn", "Chris Pratt, Vin Diesel", "121 min"),
    ("Top Gun: Maverick", "2022", "Action|Drama", "Teen", "A+", "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past.", "Joseph Kosinski", "Tom Cruise, Jennifer Connelly", "130 min"),
    ("John Wick", "2014", "Action|Crime|Thriller", "18+", "A", "An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took his car.", "Chad Stahelski", "Keanu Reeves, Michael Nyqvist", "101 min"),
    ("A Quiet Place", "2018", "Drama|Horror|Sci-Fi", "Teen", "A", "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.", "John Krasinski", "Emily Blunt, John Krasinski", "90 min"),
    ("The Conjuring", "2013", "Horror|Mystery|Thriller", "18+", "A", "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.", "James Wan", "Patrick Wilson, Vera Farmiga", "112 min"),
    ("It", "2017", "Horror", "18+", "B+", "In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster.", "Andy Muschietti", "Bill Skarsgård, Jaeden Martell", "135 min"),
    ("Hereditary", "2018", "Drama|Horror|Mystery", "18+", "A", "A grieving family is haunted by tragic and disturbing occurrences.", "Ari Aster", "Toni Collette, Milly Shapiro", "127 min"),
    ("Knives Out", "2019", "Comedy|Crime|Drama", "Teen", "A", "A detective investigates the death of a patriarch of an eccentric, combative family.", "Rian Johnson", "Daniel Craig, Chris Evans", "130 min"),
    ("The Social Network", "2010", "Biography|Drama", "Teen", "A", "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.", "David Fincher", "Jesse Eisenberg, Andrew Garfield", "120 min"),
    ("The Wolf of Wall Street", "2013", "Biography|Comedy|Crime", "18+", "A", "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime.", "Martin Scorsese", "Leonardo DiCaprio, Jonah Hill", "180 min"),
    ("Barbie", "2023", "Adventure|Comedy|Fantasy", "Teen", "A", "Barbie suffers a crisis that leads her to question her world and her existence.", "Greta Gerwig", "Margot Robbie, Ryan Gosling", "114 min"),
    ("The Truman Show", "1998", "Comedy|Drama", "Teen", "A+", "An insurance salesman discovers his whole life is actually a reality TV show.", "Peter Weir", "Jim Carrey, Ed Harris", "103 min"),
    ("Eternal Sunshine of the Spotless Mind", "2004", "Drama|Romance|Sci-Fi", "18+", "A+", "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.", "Michel Gondry", "Jim Carrey, Kate Winslet", "108 min"),
    ("500 Days of Summer", "2009", "Comedy|Drama|Romance", "Teen", "A", "An offbeat romantic comedy about a woman who doesn't believe true love exists, and the young man who falls for her.", "Marc Webb", "Zooey Deschanel, Joseph Gordon-Levitt", "95 min"),
    ("Before Sunrise", "1995", "Drama|Romance", "18+", "A+", "A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna.", "Richard Linklater", "Ethan Hawke, Julie Delpy", "101 min"),
    ("The Notebook", "2004", "Drama|Romance", "Teen", "B+", "A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated.", "Nick Cassavetes", "Gena Rowlands, James Garner", "123 min"),
    ("Titanic", "1997", "Drama|Romance", "Teen", "A+", "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", "James Cameron", "Leonardo DiCaprio, Kate Winslet", "194 min"),
    ("Avatar", "2009", "Action|Adventure|Fantasy", "Teen", "A", "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.", "James Cameron", "Sam Worthington, Zoe Saldana", "162 min"),
    ("Aliens", "1986", "Action|Adventure|Sci-Fi", "18+", "A+", "Fifty-seven years after surviving an apocalyptic attack aboard her space vessel, Ellen Ripley awakes from hyper-sleep and tries to warn anyone who will listen about the predators.", "James Cameron", "Sigourney Weaver, Michael Biehn", "137 min"),
    ("Alien", "1979", "Horror|Sci-Fi", "18+", "A+", "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.", "Ridley Scott", "Sigourney Weaver, Tom Skerritt", "117 min"),
    ("Terminator 2: Judgment Day", "1991", "Action|Sci-Fi", "18+", "A+", "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced and powerful cyborg.", "James Cameron", "Arnold Schwarzenegger, Linda Hamilton", "137 min"),
    ("Back to the Future", "1985", "Adventure|Comedy|Sci-Fi", "Family", "A+", "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend.", "Robert Zemeckis", "Michael J. Fox, Christopher Lloyd", "116 min"),
    ("Rocky", "1976", "Drama|Sport", "Teen", "A", "A small-time Philadelphia boxer gets a supremely rare chance to fight the world heavyweight champion in a bout in which he strives to go the distance for his self-respect.", "John G. Avildsen", "Sylvester Stallone, Talia Shire", "120 min"),
    ("The Departed", "2006", "Crime|Drama|Thriller", "18+", "A", "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.", "Martin Scorsese", "Leonardo DiCaprio, Matt Damon", "151 min"),
    ("Heat", "1995", "Action|Crime|Drama", "18+", "A+", "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.", "Michael Mann", "Al Pacino, Robert De Niro", "170 min"),
    ("Se7en", "1995", "Crime|Drama|Mystery", "18+", "A+", "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.", "David Fincher", "Morgan Freeman, Brad Pitt", "127 min"),
    ("Zodiac", "2007", "Crime|Drama|Mystery", "18+", "A", "In the late 1960s/early 1970s, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.", "David Fincher", "Jake Gyllenhaal, Robert Downey Jr.", "157 min"),
    ("Prisoners", "2013", "Crime|Drama|Mystery", "18+", "A", "When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads.", "Denis Villeneuve", "Hugh Jackman, Jake Gyllenhaal", "153 min"),
    ("Gone Girl", "2014", "Drama|Mystery|Thriller", "18+", "A", "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.", "David Fincher", "Ben Affleck, Rosamund Pike", "149 min"),
    ("Arrival", "2016", "Drama|Mystery|Sci-Fi", "Teen", "A+", "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", "Denis Villeneuve", "Amy Adams, Jeremy Renner", "116 min"),
    ("Blade Runner 2049", "2017", "Action|Drama|Mystery", "18+", "A", "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.", "Denis Villeneuve", "Ryan Gosling, Harrison Ford", "164 min")
]

# Write to file
with open(METADATA_PATH, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["movie_id", "title", "year", "genres", "age_category", "edge_rating", "description", "director", "cast", "runtime", "poster_url"])
    for i, m in enumerate(movies):
        poster = f"https://image.tmdb.org/t/p/w500/{random.choice(['2blXUyUVXQfM6nJbJ1wL86wL6j4.jpg', 'qJ2tW6WMUDux911r6m7haRef0WH.jpg', '8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg', 'pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg'])}"
        # The poster_url will be handled in UI. 
        # Using a dummy realistic-looking placeholder image in UI is better, but let's just generate a TMDB-like structure or just empty strings.
        poster_url = f"https://picsum.photos/seed/{i+100}/500/750" 
        writer.writerow([i+1, m[0], m[1], m[2], m[3], m[4], m[5], m[6], m[7], m[8], poster_url])

print(f"Generated {len(movies)} movies in {METADATA_PATH}")
